### PR TITLE
adding additional guidance

### PR DESCRIPTION
**Pull request by afizzycola**
Including powerpoint guidance commisioned by DSTL:
1. Extending IES4
2. Exploring different instantiation patterns used in IES
3. Examples pack

### CODE REVIEW

**Review by paulc-dstl — CHANGES_REQUESTED** [review]
Not sure having guidance docs in a proprietary pptx format is most helpful. As these are all static docs, no need for powerpoint - could we move to using pdf for all such material please?

**Comment by afizzycola** [comment]
> Not sure having guidance docs in a proprietary pptx format is most helpful. As these are all static docs, no need for powerpoint - could we move to using pdf for all such material please?

I have now replaced the pptx versions of the additional guidance docs with PDF equivalents

**Review by paulc-dstl — APPROVED** [review]

**Comment by MonkeyChap** [comment]
Looks good

**Review by MonkeyChap — APPROVED** [review]

**Comment by paulc-dstl** [comment]
Just to confirm, which of the other reports/docs/papers from last year might also be usefully added?

**Comment by paulc-dstl** [comment]
@afizzycola are you able to sign the commits then this can be merged...? TIA :-)

**Review by Bec-SU — APPROVED** [review]

**Review by Bec-SU — APPROVED** [review]

**Review by rebecca-dstl — APPROVED** [review]

**Pull request merged**
