### PR TITLE
[Minor] The image link URLs are no longer working. 

### PR DESCRIPTION
**Pull request by TelicentPaul**
Better to use the local equivalents.

### CODE REVIEW

**Review by MonkeyChap — APPROVED** [review]

**Review by paulc-dstl — APPROVED** [review]
This solution makes the links relative rather than absolute, which is necessary to avoid broken links.

**Comment by paulc-dstl** [comment]
Just catching up on github, noticed this is lurking. Does this just require commits to be signed to fix...? @TelicentPaul @afizzycola 
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by metazool** [comment]
just watched a nice talk about Arup's use of this ontology to back a "digital twin" for building energy use certification. you should merge this PR, show the project is alive! why require the commit signing?

**Comment by MonkeyChap** [comment]
> just watched a nice talk about Arup's use of this ontology to back a "digital twin" for building energy use certification. you should merge this PR, show the project is alive! why require the commit signing?

Ooh - haven't seen that. Can you post the link to the video ?

**Comment by metazool** [comment]
> Ooh - haven't seen that. Can you post the link to the video ?

It was an in-person talk / demo at this event https://thegeomob.com/post/oct-1st-2024-geomobedi-details - can't find details of the project online...

**Comment by TelicentPaul** [comment]
Implementing it again with signed commit - https://github.com/dstl/IES4/pull/10

**Comment by paulc-dstl** [comment]
> ... why require the commit signing?

Hi @metazool! Policy on the repo I'm afraid; Simple enough to work with once set up though. All best :-)

**Pull request closed without merging**
